spring.application.name=smartcity
spring.datasource.url=jdbc:mysql://smartcity-db-asthatapariya05-e880.d.aivencloud.com:26282/defaultdb?ssl-mode=REQUIRED

spring.datasource.username=avnadmin
spring.datasource.password=AVNS_vx9JY_4k0zmirW6AsJv
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080